config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resource :profiles, only: [:edit, :update]
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  } 

  root 'tasks#index'
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :verify_password, only: [:update]
  before_action :set_user

  def edit
  end

  def update
    if @user.update(params_user)
      flash[:notice] = 'Profile updated successfully'
      redirect_to edit_profiles_path
    else
      flash[:error] = @user.errors.full_messages.join(', ')
      render :edit
    end
  end  

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def params_user
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :avatar)
  end

  def verify_password
    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].extract!(:password, :password_confirmation)
    end
  end
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/profiles/edit.html.erb
<% if flash[:notice].present? || flash[:error].present? %>
  <script>
    toastr.options.positionClass = 'toast-bottom-right';
    toastr.options.closeButton = true;
    toastr.options.progressBar = true;
    toastr.options.timeOut = 5000;

    <% if flash[:notice].present? %>
      toastr.success("<%= j flash[:notice] %>");
    <% end %>

    <% if flash[:error].present? %>
      <% flash[:error].split(',').each do |message| %>
        toastr.error("<%= j message.strip %>");
      <% end %>
    <% end %>
  </script>
<% end %>

<div class="container container-sm" style="max-width: 540px;">
  <%= form_with(url: profiles_path, model: @user, local: true	) do |f| %>
    <div class="card shadow rounded" >
      <div class="row">
        <div class="p-4 mb-4">
          <div class="card-header bg-transparent">
            <h2 class="card-title text-center">Editting User Profile</h2>
          </div>
          <div class="card-body">
            <div class="mb-3">
              <%= f.label :first_name, class:"form-label"%><br />
              <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name", class: "form-control" %>
            </div>

            <div class="mb-3">
              <%= f.label :last_name, class:"form-label"%><br />
              <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name", class: "form-control" %>
            </div>

            <div class="mb-3">
              <%= f.label :email, class:"form-label", for:"disabledField" %><br />
              <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control", id:"disabledInput", disabled: true %>
            </div>

            <div class="mb-3">
              <%= f.label :password, class:"form-label no-hover-bg" %><br />
              <%= f.password_field :password, autocomplete: "current-password", class: "form-control" %>
            </div>

            <div class="mb-3">
              <%= f.label :password_confirmation, class:"form-label no-hover-bg" %><br />
              <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control" %>
            </div>

            <div class="mb-3">
              <%= f.label :avatar, class: "form-label" %><br>
              <%= f.file_field :avatar, class: "form-control" %>
            </div>
          </div>

          <div class="card-footer bg-transparent">
            <div class="d-grid">
              <%= f.submit "Update", class: "btn btn-primary" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>