config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resource :profiles, only: [:edit, :update]
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  } 

  root 'tasks#index'
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  validates :title, length: { maximum: 50 }, presence: true
  validates :body,length: { maximum: 100 }, presence: true
  validates :delivery_date, presence: true

  validate :check_delivery_date, on: :create

  validate :check_reminder_validity, on: :update

  def check_delivery_date
    if delivery_date.present? && delivery_date.past?
      errors.add(:delivery_date, "must be a future date")
    end
  end

  def check_reminder_validity
    if reminder? && delivery_date.past?
      errors.add(:reminder, "cannot be set for a task that is already overdue")
    end
  end
  
  def self.ransackable_attributes(auth_object = nil)
    ["body", "completed", "created_at", "delivery_date", "id", "title", "updated_at", "user_id"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["user"]
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /tasks or /tasks.json
  def index
    @query = current_user.tasks.ransack(params[:q]) #retorna apenas as tarefas do usuário atual. aplica a pesquisa usando o Ransack
    @tasks = @query.result(distinct: true).page(params[:page]) #filtra os registros com base nos critérios de pesquisa do Ransack e do Kaminari para paginar os resultados para obter uma lista paginada de tarefas que correspondem aos critérios de pesquisa definidos pelo usuário.
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
    @task.delivery_date = Date.today
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /tasks/1/edit
  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)
    @task.user = current_user

    respond_to do |format|
      if @task.save
        send_task_reminder_email(@task) if @task.reminder
        format.html { redirect_to root_path, notice: "Task was successfully created.", toastr: "success" }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        send_task_reminder_email(@task) if @task.reminder
        format.html { redirect_to root_path, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html do
          flash.now[:alert] = @task.errors.full_messages.join(", ")
          redirect_to root_path
        end
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed.", toastr: "success" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def send_task_reminder_email(task)
      return if task.completed?
      
      TaskMailer.task_reminder_email(task).deliver_now
    end    

    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :body, :delivery_date, :completed, :reminder)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_edit.html.erb
<div id="card-modal">
  <div class="modal-header">
    <h3 class="modal-title"><%= action %></h3>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>

  <%= render 'form', task: @task %>
</div>

app/views/tasks/_footer.html.erb
<div class="footer bg-dark">
  <p>Copyright © 2023 Lucas on Rails – Todos os direitos reservados.</p>
  
  <ul class="social-links">
    <!-- LinkedIn -->
    <%= link_to "https://www.linkedin.com/in/lucasonrails", target: "_blank", class:"icons" do %>
      <i class="fab fa-linkedin"></i>
    <% end %>

    <!-- Instagram -->
    <%= link_to "https://www.instagram.com/lucas23_ofc/", target: "_blank", class:"icons" do %>
      <i class="fab fa-instagram"></i>
    <% end %>

    <!-- GitHub -->
    <%= link_to "https://github.com/Lucas-SilvaGit", target: "_blank", class:"icons" do %>
      <i class="fab fa-github"></i>
    <% end %>
  </ul>
</div>

app/views/tasks/_form.html.erb
<%= form_with(model: task, html: { class: "needs-validation" }) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="modal-body">
    <div class="mb-3">
      <%= form.label :title, class:"form-label" %>
      <%= form.text_field :title, class:"form-control", placeholder:"Enter title here!", required: true %>
    </div>

    <div class="mb-3">
      <%= form.label :body, class:"form-label" %>
      <%= form.text_area :body, class:"form-control", placeholder:"Enter task description here!", required: true %>
    </div>

    <div class="mb-3 d-flex ">
      <div>
      <%= form.label :delivery_date, class:"form-label" %>
      <%= form.date_field :delivery_date, class: "form-control", id: "delivery_date_field", required: true %>
      </div>

      <div>
      <%= form.label :reminder, class: "form-label" %>
      <%= form.check_box :reminder, class: "form-check-input" %>
      </div>
    </div>

    <div class="mb-3">
      <%= form.label :completed, class:"form-label" %>
      <%= form.check_box :completed, class: "form-check-input"%>
    </div>
  </div>

  <div class="modal-footer">
    <%= form.submit "Save", class:"btn btn-primary" %>
  </div>
<% end %>

<script>
  $(document).ready(function() {
    $("#delivery_date_field").datepicker
  });
</script>

app/views/tasks/_form_search.html.erb
<%= search_form_for(@query, url: tasks_path, method: :get, class: "d-flex mx-auto" ) do |f| %>
    <%= f.search_field :title_or_body_i_cont_any, placeholder: "Search...", class:"form-control me-2" %>
    <%= f.submit "Search!", class:"btn btn-outline-primary" %>
<% end %>

app/views/tasks/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand no-hover-bg" href="<%= tasks_path %>">Just Do It</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% unless (params[:action] == 'edit' && params[:controller] == 'profiles') || params[:action] == 'update' %>
        <%= render 'form_search' %>
      <% end %>
      <ul class="navbar-nav mb-2 mb-lg-0 ms-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle no-hover-bg" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <% if current_user.first_name.present? || current_user.last_name.present? %>
              <%= @current_user.full_name %>
              <% else %>
                <%= @current_user.email %>
              <% end %>
              <% if @current_user.avatar.attached? %>
                <img src="<%= url_for(@current_user.avatar) %>" alt="Avatar" class="rounded-circle" style="width: 30px; height: 30px; margin-left:20px;">
              <% else %>
                <img src="../img/avatar.jpg" alt="Default Avatar" class="rounded-circle" style="width: 30px; height: 30px; margin-left:20px;">
            <% end %>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>
              <a class="dropdown-item">
                <%= link_to edit_profiles_path, class: "btn" do %>
                  Profile
                <% end %>
              </a>
            </li>
            <li><hr class="dropdown-divider"></li>
            <li>
              <a class="dropdown-item">
                <%= link_to destroy_user_session_path, method: :delete, class: "btn" do %>
                  <i class="fas fa-sign-out-alt fs-6"></i>
                  Logout
                <% end %>
              </a>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/tasks/_new.html.erb
<div id="card-modal">
  <div class="modal-header">
    <h3 class="modal-title"><%= action %></h3>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>

  <%= render 'form', task: @task %>
</div>

app/views/tasks/edit.js.erb
var modal = new bootstrap.Modal(document.querySelector("#modal-report"));
var modalContent = document.querySelector("#modal-report .modal-content");
modalContent.innerHTML = "<%= j (render 'edit', action: 'Editing Task') %>";
modal.show();

app/views/tasks/index.html.erb
<% if flash[:notice].present? %>
  <script>
    toastr.options.positionClass = 'toast-bottom-right';
    toastr.options.closeButton = true;
    toastr.options.progressBar = true;
    toastr.options.timeOut = 2000;
    toastr.success("<%= j flash[:notice] %>");
  </script>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-12 mt-4 mb-4 d-flex justify-content-between align-items-center">
      <%= link_to new_task_path, { remote: true, 'data-toggle': "modal", 'data-target': '#modal-report', action: 'new', class: 'btn btn-primary text-light' } do %>
        <i class="fas fa-plus"></i> New Task
      <% end %>
    </div>
    <% @tasks.each do |task| %>
      <div class="col-md-12">
        <div class="card shadow-sm ps-2 mb-3 rounded">
          <div class="card-body d-flex justify-content-between align-items-center">
            <h5 class="card-title col-md-8"><%= task.title %></h5>
            <div class="actions d-flex col-md-4">

              <i class="fa-solid fa-circle me-3 mt-2 custom-cursor-pointer task-status-<%= task_status_class(task) %>" 
                data-bs-toggle="tooltip" data-bs-placement="top" data-bs-html="true" data-bs-original-title="
                <span><%= task_status_class(task).capitalize %></span> </br> 
                <span><%= task.delivery_date.strftime('%d/%B') %></span>">
              </i>

              <% if task.reminder %>
                <i class="fa-solid fa-bell me-3 mt-2 custom-cursor-pointer " data-bs-toggle="tooltip" data-bs-placement="top" data-bs-html="true" data-bs-original-title="Reminder ON"></i>
              <% else %>
                <i class="fa-regular fa-bell me-3 mt-2 custom-cursor-pointer " data-bs-toggle="tooltip" data-bs-placement="top" data-bs-html="true" data-bs-original-title="Reminder OFF"></i>
              <% end %>

              <%= simple_form_for(task, remote: true) do |f| %>
                <%= f.label :completed, "Completed:", class: 'form-check-label fw-bolder me-2' %>
                <%= f.check_box :completed, class: 'form-check-input me-4 mt-2' %>
                <button class="btn btn-outline-primary  me-2">
                  <i class="fa-solid fa-arrows-rotate"></i>
                </button>

                <%= link_to edit_task_path(task), remote: true, 'data-toggle': "modal", 'data-target': '#modal-report', action: 'edit', class: 'btn btn-outline-secondary  me-2' do %>
                  <i class="fas fa-edit"></i>
                <% end %>
                
                <%= link_to task, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger  me-2' do %>
                  <i class="fas fa-trash"></i>
                <% end %>
              <% end %>

            </div>
          </div>
        </div>
      </div>
    <% end %>
    <%= paginate @tasks %>
  </div>
  <br>
</div>

<div class="modal modal-blur fade" id="modal-report" tabindex="-1" style="display: none;" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
    <div class="modal-content"></div>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function(event) {
    var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'));
    var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
      return new bootstrap.Tooltip(tooltipTriggerEl);
    });
  });
</script>

app/views/tasks/new.js.erb
var modal = new bootstrap.Modal(document.querySelector("#modal-report"));
var modalContent = document.querySelector("#modal-report .modal-content");
modalContent.innerHTML = "<%= j (render 'new', action: 'New Task') %>";
modal.show();

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @task.body %>
</p>

<p>
  <strong>Delivery date:</strong>
  <%= @task.delivery_date %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @task.completed %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>